version: "3"

services: 

    mysql:
        image: mysql:8.0
        command:  
            --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_DATABASE: testdb
            MYSQL_USER: root
            MYSQL_PASSWORD: example
            MYSQL_ROOT_PASSWORD: example
        ports:
            - "3306:3306"
        networks: 
            - rest-api-network
        restart: always

    rest-api-app:
        build:
            dockerfile: Dockerfile.dev
            context: ./rest-api-app
        ports: 
            - "5000:5000"
        environment: 
            MYSQL_ROOT_PASSWORD: example
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: example
        depends_on: 
            - mysql
        networks: 
            - rest-api-network

networks: 
    rest-api-network: